# Generated by Django 5.1.7 on 2025-03-21 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryReksadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reksadana',
            fields=[
                ('id_reksadana', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nav', models.IntegerField()),
                ('aum', models.IntegerField()),
                ('tingkat_resiko', models.CharField(choices=[('Konservatif', 'Konservatif'), ('Moderat', 'Moderat'), ('Agresif', 'Agresif')], default='Konservatif', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reksadana_rest.categoryreksadana')),
                ('kustodian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kustodian_reksadana', to='reksadana_rest.bank')),
                ('penampung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penampung_reksadana', to='reksadana_rest.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('nominal', models.IntegerField()),
                ('waktu_pembelian', models.DateTimeField()),
                ('id_reksadana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reksadana_rest.reksadana')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryReksadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nav', models.IntegerField()),
                ('aum', models.IntegerField()),
                ('id_reksadana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reksadana_rest.reksadana')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDibeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('nominal', models.IntegerField()),
                ('waktu_pembelian', models.DateTimeField()),
                ('id_reksadana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reksadana_rest.reksadana')),
            ],
        ),
    ]
