# Generated by Django 5.1.7 on 2025-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyreksadana',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
