# Generated by Django 5.1.7 on 2025-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana_rest', '0002_alter_historyreksadana_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyreksadana',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
